config/routes.rb
# frozen_string_literal: true

Improvcoaches::Application.routes.draw do
  root to: 'home#index'
  get '/about', to: 'home#about'
  get '/splash', to: 'home#splash'
  match '/search', to: 'search#search', via: %i[post get]
  get '/improv-books', to: 'home#resources', as: 'resources'

  controller :auth do
    get  'login' => :new
    post 'login' => :create
    get  'logout' => :destroy

    get 'link' => :link
    post 'link' => :confirm_link
  end

  # Omniauth
  get 'auth/:provider/callback', to: 'auth#create', from_facebook: true
  get 'auth/failure', to: 'auth#failure'
  get 'signout', to: 'auth#destroy', as: 'signout'

  controller :users do
    get 'join' => :new
    get 'profile' => :show, profile: true
    get 'profile/invites' => :invites
    post 'profile/invites' => 'invites#invite_send'
    get 'profile/invites/:code/resend' => 'invites#resend', as: 'profile_invite_resend', defaults: { format: 'js' }
    get 'profile/invites/:code/cancel' => 'invites#cancel', as: 'profile_invite_cancel', defaults: { format: 'js' }
    get 'profile/edit' => :edit
    get 'profile/unlink' => :unlink
    get 'profile/destroy' => :destroy
    get 'profile/edit/improv' => :edit_improv
    get 'profile/edit/schedule' => :edit_schedule
    get 'profile/edit/password' => :edit_password
    post 'profile/update' => :update
    delete 'profile/edit/avatar' => :delete_avatar
  end

  controller :schedules do
    post 'profile/edit/schedule' => :update
  end

  controller :invites do
    get 'invite/:code' => :landing, as: 'invite_landing'
    get 'invite/:code/accept' => :accept, as: 'invite_accept'
  end

  resources :users, path: 'coaches' do
    controller :ratings do
      get 'like' => :like, defaults: {format: :js }
      get 'dislike' => :dislike, defaults: {format: :js }
      get 'bookmark' => :bookmark, defaults: {format: :js }
    end

    get 'email' => :email
    post 'email' => :email_send, defaults: {format: :js }
    post 'comment' => :comment_send, defaults: {format: :js }
  end

  resources :spaces do
    patch 'image' => :add_image
    delete 'image/:id' => :delete_image
  end

  resources :password_resets
  resources :theatres
  resources :substitution_requests
end

app/models/invite.rb
# == Schema Information
#
# Table name: invites
#
#  id         :integer          not null, primary key
#  code       :string(255)
#  owner_id   :integer
#  recipient  :string(255)
#  status     :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Invite < ActiveRecord::Base
  validates :owner, presence: true
  validates :code, presence: true, uniqueness: true
  validates :status, inclusion: { in: ['free', 'pending', 'used'] }


  has_one :user
  belongs_to :owner, class_name: :User

  after_initialize :defaults

  scope :free, -> { where(status: 'free') }
  scope :pending, -> { where(status: 'pending') }
  scope :used, -> { where(status: 'used') }
  scope :sent, -> { where("status = ? OR status = ?", "pending", "used") }

  def to_param
    code
  end

  def defaults
  	self.status ||= 'free'
    self.code ||= SecureRandom.hex(8)
  end

  def deliver
    InviteMailer.send_invitation(self).deliver
  end

end

app/controllers/invites_controller.rb
class InvitesController < ApplicationController
  before_filter :require_login, except: [:landing]

  def landing
    @invite = Invite.find_by_code(params[:code])

    if @invite.owner.city != current_city
      redirect_to subdomain: @invite.owner.city.subdomain
    else
      if @invite && @invite.status == 'pending'
        @user = User.new(params[:user]) # Hack till I figure out login
        session[:redirect_on_login] = invite_accept_url code: params[:code]

        flash.keep # Preserve to next request
      else
        redirect_to root_url, { flash: { alert: 'This invite has already been used.'} }
      end
    end
  end

  def invite_send
    to = params[:email]

    # Admins get free invites.
    current_user.add_invite if current_user.is_admin? && current_user.invites.free.count == 0

    if current_user.invites.free.count > 0
      if ValidatesEmailFormatOf.validate_email_format(to) == nil
        @invite = current_user.invites.free.first
        @invite.status = 'pending'
        @invite.recipient = to
        @invite.save!
        @invite.deliver

        @message = "#{to} has been invited to ImprovCoaches.  Thanks!"
        @level = 'success'
      else
        @message = "#{to} is not a valid email address."
        @level = 'danger'
      end
    else
      @message = 'You don\'t have any invites available.'
      @level = 'danger'
    end

    respond_to do |format|
      format.js
    end
  end
  

  def accept
    return_to_url = root_url
    @invite = Invite.find_by_code(params[:code])

    redirect_hash = { flash: {} }
    redirect_flash = redirect_hash[:flash]

    if @invite && @invite.status == 'pending'
      if !current_user.is_coach
        @invite.status = 'used'
        @invite.save!

        u = @user = User.find(current_user.id)

        u.is_coach = 't'
        u.is_improv = 't'
        u.city = @invite.owner.city
        u.save

        redirect_flash[:success] = 'Welcome to ImprovCoaches!  Be sure to add a bio, schedule, and your experience to help users discover your profile.'
      else
        redirect_flash[:alert] = 'Your account has already been upgraded.'
      end

      if @invite.owner.city != current_city
        return_to_url = profile_edit_url( subdomain: @invite.owner.city.subdomain )
      else
        return_to_url = profile_edit_url
      end
    else
      redirect_flash[:alert] = 'That invite has already been used.'
    end

    respond_to do |format|
      format.html { redirect_to return_to_url, redirect_hash }
    end
  end

  def resend
    @invite = Invite.find_by_code(params[:code])
    @invite.deliver

    respond_to do |format|
      format.js
    end
  end

  def cancel
    @invite = Invite.find_by_code(params[:code])
    if @invite.status != 'used'
      @invite.recipient = nil
      @invite.status = 'free'
      @invite.save!
    end

    respond_to do |format|
      format.js
    end
  end
end

app/helpers/invites_helper.rb
module InvitesHelper
end

app/views/invites/_invite.html.erb
<tr id="invite_<%= invite.id %>">
	<td><%= invite.recipient %></td>
	<td><%= invite.status %></td>
	<td><!-- empty --></td>
	<td>
		<% if invite.status == "pending" %>
			<%= link_to  profile_invite_resend_path(invite), remote: true do %>
				<span class="glyphicon glyphicon-refresh" ></span>
			<% end %>
		<% end %>
	</td>
	<td>
		<% if invite.status == "pending" %>
			<%= link_to  profile_invite_cancel_path(invite), remote: true do %>
				<span class="glyphicon glyphicon-remove" ></span>
			<% end %>
		<% end %>
	</td>
</tr>

app/views/invites/cancel.js.erb
<%= render partial: 'shared/alert', locals: { message: "Your invite has been cancelled.", level: "success"}  %>
$("#invite_<%= @invite.id %>").remove();

app/views/invites/invite_send.js.erb
$('#invite textarea').val("");
<%= render partial: "shared/alert", locals: { level: @level, message: @message} %>
<% if @level == "success" %>
	$("#invites tr:last").after("<%= escape_javascript(render partial: 'invite', object: @invite )%>");
<% end %>

app/views/invites/landing.html.erb
<div id="invite">
	<div class="jumbotron">
		<div class="container">
			<h1>So you want to be a coach, huh?</h1>
		
			<p>That's great.  Really.  But don't thank me.  Thank <%= @invite.owner.name %> for thinking you've got the chops.</p>
			<br />
			<div class="panel panel-success">
				<div class="panel-heading">
					A few things you should know:
				</div>
				<div class="panel-body">
					<ul>
						<li>The more information you provide, the easier it will be for people to find you.</li>
						<li>Want gigs?  Keep your schedule updated.</li>
						<li>You'll be rated by other users.  It's 100% anonymous, but it'll appear on your profile.</li>
						<li>The more people using ImprovCoaches, the better it is for everyone.  Spread the word in your practices and community.</li>
						<li>If you ever see <%= link_to "this handsome devil", user_url(1) %>, toss him a high-five.</li>
					</ul>
				</div>
				<% if current_user %>
					<div class = 'text-center form-group'>
						<%= link_to invite_accept_path(@invite) do %>
							<button class="btn btn-lg btn-success">
								<span class="glyphicon glyphicon-thumbs-up"></span> Accept Invite
							</button>
						<% end %>
					</div>
				<% end %>
			</div>
		</div>
	</div>

	<% unless current_user %>
		<div class="container">
			<div class="row">
				<div class="col-sm-12 col-md-6">
					<div class="panel panel-primary">
						<div class="panel-heading">
							Create an Account or Login with Facebook
						</div>
						<div class="panel-body" id="facebook">
	    					<%= link_to "/auth/facebook" do%>
								<button id="fb_login" class="btn btn-lg btn-facebook">
									<span class="icon-facebook"></span> | Login with Facebook
								</button>
							<% end %>
						</div>
					</div>
				</div>

				<div class="col-sm-12 col-md-6">
					<div class="panel panel-primary">
						<div class="panel-heading">
							Log In to an Existing Account
						</div>
						<div class="panel-body">
							<%= render partial: 'auth/login', locals: { invite_code: @invite.code} %>
						</div>
					</div>
					<h3 class='text-center'>OR</h3>
					<div class="panel panel-primary">
						<div class="panel-heading">
							Create an Account without Facebook
						</div>
						<div class="panel-body">
							<%= render partial: 'users/register', locals: { invite_code: @invite.code } %>
						</div>
					</div>
				</div>
			</div>
		</div>
	<% end %>
</div>

app/views/invites/resend.js.erb
<%= render partial: 'shared/alert', locals: { message: "Your invite has been resent.", level: "success"}  %>