config/routes.rb
# frozen_string_literal: true

Improvcoaches::Application.routes.draw do
  root to: 'home#index'
  get '/about', to: 'home#about'
  get '/splash', to: 'home#splash'
  match '/search', to: 'search#search', via: %i[post get]
  get '/improv-books', to: 'home#resources', as: 'resources'

  controller :auth do
    get  'login' => :new
    post 'login' => :create
    get  'logout' => :destroy

    get 'link' => :link
    post 'link' => :confirm_link
  end

  # Omniauth
  get 'auth/:provider/callback', to: 'auth#create', from_facebook: true
  get 'auth/failure', to: 'auth#failure'
  get 'signout', to: 'auth#destroy', as: 'signout'

  controller :users do
    get 'join' => :new
    get 'profile' => :show, profile: true
    get 'profile/invites' => :invites
    post 'profile/invites' => 'invites#invite_send'
    get 'profile/invites/:code/resend' => 'invites#resend', as: 'profile_invite_resend', defaults: { format: 'js' }
    get 'profile/invites/:code/cancel' => 'invites#cancel', as: 'profile_invite_cancel', defaults: { format: 'js' }
    get 'profile/edit' => :edit
    get 'profile/unlink' => :unlink
    get 'profile/destroy' => :destroy
    get 'profile/edit/improv' => :edit_improv
    get 'profile/edit/schedule' => :edit_schedule
    get 'profile/edit/password' => :edit_password
    post 'profile/update' => :update
    delete 'profile/edit/avatar' => :delete_avatar
  end

  controller :schedules do
    post 'profile/edit/schedule' => :update
  end

  controller :invites do
    get 'invite/:code' => :landing, as: 'invite_landing'
    get 'invite/:code/accept' => :accept, as: 'invite_accept'
  end

  resources :users, path: 'coaches' do
    controller :ratings do
      get 'like' => :like, defaults: {format: :js }
      get 'dislike' => :dislike, defaults: {format: :js }
      get 'bookmark' => :bookmark, defaults: {format: :js }
    end

    get 'email' => :email
    post 'email' => :email_send, defaults: {format: :js }
    post 'comment' => :comment_send, defaults: {format: :js }
  end

  resources :spaces do
    patch 'image' => :add_image
    delete 'image/:id' => :delete_image
  end

  resources :password_resets
  resources :theatres
  resources :substitution_requests
end

app/models/space.rb
# == Schema Information
#
# Table name: spaces
#
#  id             :integer          not null, primary key
#  name           :string(255)
#  description    :text
#  city_id        :integer
#  rating         :decimal(, )
#  website_link   :string(255)
#  yelp_link      :string(255)
#  facebook_link  :string(255)
#  address        :string(255)
#  address_2      :string(255)
#  zip            :string(255)
#  real_city      :string(255)
#  state          :string(255)
#  phone          :string(255)
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  slug           :string(255)
#  is_rehearsal   :boolean          default(TRUE)
#  is_performance :boolean          default(FALSE)
#  email          :string(255)
#

class Space < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, use: [:history]

  has_many :space_images
  belongs_to :city

  validates :name, presence: true, uniqueness: true

  
  def compiled_address
    "#{address} #{address_2}  #{real_city}  #{state} #{zip}"
  end
end

app/controllers/spaces_controller.rb
class SpacesController < ApplicationController
  # GET /spaces
  # GET /spaces.json

  before_filter :require_admin, except: [:index, :show]

  def index
    @spaces = current_city.spaces.paginate(page: params[:page], per_page: 10)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @spaces }
    end
  end

  # GET /spaces/1
  # GET /spaces/1.json
  def show
    @space = Space.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @space }
    end
  end

  # GET /spaces/new
  # GET /spaces/new.json
  def new
    @space = Space.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @space }
    end
  end

  # GET /spaces/1/edit
  def edit
    @space = Space.find(params[:id])
  end

  # POST /spaces
  # POST /spaces.json
  def create
    @space = Space.new(params[:space])

    respond_to do |format|
      if @space.save
        format.html { redirect_to @space, notice: 'Space was successfully created.' }
        format.json { render json: @space, status: :created, location: @space }
      else
        format.html { render action: "new" }
        format.json { render json: @space.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /spaces/1
  # PUT /spaces/1.json
  def update
    @space = Space.find(params[:id])

    respond_to do |format|
      if @space.update_attributes(params[:space])
        format.html { redirect_to edit_space_url(@space), notice: 'Space was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @space.errors, status: :unprocessable_entity }
      end
    end
  end

  def add_image
    @space = Space.find(params[:space_id])

    respond_to do |format|
      space_image = SpaceImage.new
      space_image.space_id = @space.id
      space_image.photo = params[:photo]

      if space_image.save
        format.html { redirect_to edit_space_url(@space), notice: 'Image added.' }
        format.json { head :no_content }
      else
        puts space_image.errors.full_messages
        format.html { redirect_to edit_space_url(@space), notice: 'Image upload failed.' }
        format.json { render json: space_image.errors, status: :unprocessable_entity }
      end
    end 
  end

  def delete_image

  end

  # DELETE /spaces/1
  # DELETE /spaces/1.json
  def destroy
    @space = Space.find(params[:id])
    @space.destroy

    respond_to do |format|
      format.html { redirect_to spaces_url }
      format.json { head :no_content }
    end
  end

  def remove_image

  end
end

app/helpers/spaces_helper.rb
module SpacesHelper
end

app/views/spaces/_form.html.erb
<div class="row">
  <div class="col-md-6">
    <%= form_for(@space, html: {class: "form-group" } ) do |f| %>
      <% if @space.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@space.errors.count, "error") %> prohibited this space from being saved:</h2>

          <ul>
          <% @space.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="field ">
        <%= f.label :name %><br />
        <%= f.text_field :name, class: "form-control" %>
      </div>
      <div class="field">
        <%= f.label :description %><br />
        <%= f.text_area :description, class: "form-control"  %>
      </div>
      <div class="field">
        <%= f.label :city_id %><br />
        <%= f.collection_select(:city_id, City.all, :id, :name, { class: "form-control" } ) %>
      </div>
      <div class="field">
        <%= f.label :rating %><br />
        <%= f.text_field :rating, class: "form-control"  %>
      </div>
      <div class="field">
        <%= f.label :website_link %><br />
        <%= f.text_field :website_link, class: "form-control"  %>
      </div>
      <div class="field">
        <%= f.label :yelp_link %><br />
        <%= f.text_field :yelp_link, class: "form-control"  %>
      </div>
      <div class="field">
        <%= f.label :facebook_link %><br />
        <%= f.text_field :facebook_link, class: "form-control"  %>
      </div>
      <div class="field">
        <%= f.label :address %><br />
        <%= f.text_field :address, class: "form-control"  %>
      </div>
      <div class="field">
        <%= f.label :address_2 %><br />
        <%= f.text_field :address_2, class: "form-control"  %>
      </div>
      <div class="field">
        <%= f.label :zip %><br />
        <%= f.text_field :zip, class: "form-control"  %>
      </div>
      <div class="field">
        <%= f.label :real_city %><br />
        <%= f.text_field :real_city, class: "form-control"  %>
      </div>
      <div class="field">
        <%= f.label :state %><br />
        <%= f.text_field :state, class: "form-control"  %>
      </div>
      <div class="field">
        <%= f.label :phone %><br />
        <%= f.text_field :phone, class: "form-control"  %>
      </div>
      <div class="field">
        <%= f.label :email %><br />
        <%= f.text_field :email, class: "form-control"  %>
      </div>
      <div class="field">
        <%= f.label :is_rehearsal, "Is Rehearsal" %>
        <%= f.check_box :is_rehearsal %>
      </div>
      <div class="field">
        <%= f.label :is_performance, "Is Performance" %>
        <%= f.check_box :is_performance %>
      </div>
      <div class="actions">
        <%= f.submit "Edit", class: "btn btn-block btn-primary" %>
      </div>
    <% end %>
  </div>

  </div>
</div>

app/views/spaces/_result.html.erb
<div class="result">
	<div class="row">
		<div class="col-md-12">
			<%= link_to space_path(space, options) do %>
				<h2><%= space.name %></h2>
			<% end %>
		</div>
	</div>
	<div class="row">
		<div class="col-md-6">
			<%= space.compiled_address %>
		</div>
		<div class="col-md-6">
			<% link_to space.phone, "tel:#{space.phone}" %>
		</div>
	</div>
</div>

app/views/spaces/edit.html.erb
<h1>Editing space</h1>

<%= render 'form' %>

<%= link_to 'Show', @space %> |
<%= link_to 'Back', spaces_path %>

app/views/spaces/index.html.erb
<% set_meta_tags title: "Spaces" %>
<h1>Spaces</h1>

<% @spaces.each do |space| %>
      <%= render partial: "spaces/result", locals: {space: space, options: {}} %>
<% end %>
<%= will_paginate @spaces %>
<br />

<% if current_user && current_user.is_admin? %>
    <%= link_to 'New Space', new_space_path %>
<% end %>
<%= mail_to 'support@improvcoaches.com', 'Suggest a Space' %>

app/views/spaces/new.html.erb
<h1>New space</h1>

<%= render 'form' %>

<%= link_to 'Back', spaces_path %>

app/views/spaces/show.html.erb
<% set_meta_tags title: @space.name, reverse: true %>
<% set_meta_tags canonical: space_url(@space) %>

<div id="show">
  <div class="container">
    <h1>
      <%= @space.name %>
    </h1>

    <div class="row">
      <div class="col-sm-12 col-md-3">
        <div id="contact" class="panel panel-primary">
          <div class="panel-heading">
            Contact
          </div>

          <div class="panel-body">
            <div class="container">
              <div id="address">
                <div>
                  <%= @space.address %>
                  <% if !@space.address_2.nil? %>
                    <%= @space.address_2 %>
                  <% end %>
                </div>
                
                <div><%= @space.real_city %>, <%= @space.state %> <%= @space.zip %></div>
                <div><%= @space.address %></div>
                
                <% unless @space.phone.nil? %>
                  <%= link_to "tel:#{@space.phone}" do%>
                    <div class="btn btn-large btn-success">
                      <span class="glyphicon glyphicon-phone"><%= @space.phone %></span> 
                    </div>
                  <% end %>
                <% end %>


                <% unless @space.website_link.nil? %>
                  <%= link_to @space.website_link do %>
                    <div class="btn btn-large btn-success">
                      <span class="glyphicon glyphicon-globe">Website</span>
                    </div>
                  <% end %>
                <% end %>

                <% unless @space.email.nil? %>
                  <%= mail_to @space.email do %>
                    <div class="btn btn-large btn-success">
                      <span class="glyphicon glyphicon-envelope">Email</span>
                    </div>
                  <% end %>
                <% end %>

               </div>

              <div>
                <ul>
                  <li>
                    <%= link_to "http://maps.google.com/?q=#{@space.compiled_address}" do %>
                      <%= image_tag '3rdparty/google_maps_logo_58.jpeg' %>
                    <% end %>
                  </li>
                  <% unless @space.yelp_link.nil? %>
                    <li>
                      <%= link_to @space.yelp_link do%>
                        <%= image_tag '3rdparty/yelp_logo_50x25.jpeg' %>
                      <% end %>
                    </li>
                  <% end %>
                  <% unless @space.facebook_link.nil? %>
                    <li>
                      <%= link_to @space.facebook_link do%>
                        <%= image_tag '3rdparty/FB-f-Logo__blue_50.png' %>
                      <% end %>
                    </li>
                  <% end %>
                </ul>
              </div>
              
              <% if current_user && current_user.is_admin? %>
                <div class="admin-only">
                  <%= link_to edit_space_path(@space)  do %>
                    <div class="btn btn-info">
                      <span class="glyphicon glyphicon-edit"></span> Edit
                    </div>
                  <% end %>

                  <%= link_to @space, method: :delete, data: { confirm: 'Are you sure?' } do %>
                    <div class="btn btn-danger">
                      <span class="glyphicon glyphicon-remvoe"></span> Remove
                    </div>
                  <% end %>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>

      <div class="col-sm-12 col-md-9">
          <div id="bio" class="panel panel-default">
            <div class="panel-heading">
              About <%= @space.name %>
            </div>
            <div class="panel-body">
              <%= simple_format @space.description %>
              <% if @space.is_rehearsal? %>
                <p>Available for Rehearsals</p>
              <% end %>

              <% if @space.is_performance? %>
                <p>Available for Performances</p>
              <% end %>
            </div>
          </div>

        <div id="feedback" class="panel panel-default">
          <div class="panel-heading">
            Feedback
          </div>
          <div class="panel-body">
            <div class="fb-comments" data-href="<%= space_url @space %>" data-num-posts="10" data-order-by="reverse_time" data-width="100%"></div>
          </div>
        </div>

        <div id="map" class="panel panel-default">
          <div class="panel-heading">
            Map
          </div>
          <div class="panel-body">
             <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyB45xIVXhmt-03fS12e2-eXn3ke3NitrO8&sensor=false"></script>
             <script type="text/javascript">
              function initialize() {
                var gc = new google.maps.Geocoder();
                gc.geocode( { address: "<%= @space.compiled_address %>"}, function(result, status){
                  var latLng = (result[0]).geometry.location;
                  var marker = new google.maps.Marker({
                    position: latLng
                  });
                  var mapOptions = {
                    center: latLng,
                    zoom: 16,
                    draggable: false,

                  };
                  var map = new google.maps.Map(document.getElementById("map-canvas"), mapOptions);
                  marker.setMap(map);
                });
              }
              google.maps.event.addDomListener(window, 'load', initialize);
            </script>
            <div id="map-canvas" style="width: 100%; height: 600px  ;">
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>