config/routes.rb
# frozen_string_literal: true

Improvcoaches::Application.routes.draw do
  root to: 'home#index'
  get '/about', to: 'home#about'
  get '/splash', to: 'home#splash'
  match '/search', to: 'search#search', via: %i[post get]
  get '/improv-books', to: 'home#resources', as: 'resources'

  controller :auth do
    get  'login' => :new
    post 'login' => :create
    get  'logout' => :destroy

    get 'link' => :link
    post 'link' => :confirm_link
  end

  # Omniauth
  get 'auth/:provider/callback', to: 'auth#create', from_facebook: true
  get 'auth/failure', to: 'auth#failure'
  get 'signout', to: 'auth#destroy', as: 'signout'

  controller :users do
    get 'join' => :new
    get 'profile' => :show, profile: true
    get 'profile/invites' => :invites
    post 'profile/invites' => 'invites#invite_send'
    get 'profile/invites/:code/resend' => 'invites#resend', as: 'profile_invite_resend', defaults: { format: 'js' }
    get 'profile/invites/:code/cancel' => 'invites#cancel', as: 'profile_invite_cancel', defaults: { format: 'js' }
    get 'profile/edit' => :edit
    get 'profile/unlink' => :unlink
    get 'profile/destroy' => :destroy
    get 'profile/edit/improv' => :edit_improv
    get 'profile/edit/schedule' => :edit_schedule
    get 'profile/edit/password' => :edit_password
    post 'profile/update' => :update
    delete 'profile/edit/avatar' => :delete_avatar
  end

  controller :schedules do
    post 'profile/edit/schedule' => :update
  end

  controller :invites do
    get 'invite/:code' => :landing, as: 'invite_landing'
    get 'invite/:code/accept' => :accept, as: 'invite_accept'
  end

  resources :users, path: 'coaches' do
    controller :ratings do
      get 'like' => :like, defaults: {format: :js }
      get 'dislike' => :dislike, defaults: {format: :js }
      get 'bookmark' => :bookmark, defaults: {format: :js }
    end

    get 'email' => :email
    post 'email' => :email_send, defaults: {format: :js }
    post 'comment' => :comment_send, defaults: {format: :js }
  end

  resources :spaces do
    patch 'image' => :add_image
    delete 'image/:id' => :delete_image
  end

  resources :password_resets
  resources :theatres
  resources :substitution_requests
end

app/models/user.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  name                   :string(255)
#  email                  :string(255)
#  is_coach               :boolean
#  bio                    :text
#  password_digest        :string(255)
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  img                    :string(255)
#  rate                   :integer
#  last_updated           :datetime
#  is_admin               :integer
#  avatar_file_name       :string(255)
#  avatar_content_type    :string(255)
#  avatar_file_size       :integer
#  avatar_updated_at      :datetime
#  auth_token             :string(255)
#  password_reset_token   :string(255)
#  password_reset_time    :datetime
#  rating                 :integer
#  uid                    :string(255)
#  oauth_token            :string(255)
#  oauth_token_expires_at :datetime
#  provider               :string(255)
#  slug                   :string(255)
#  invite_id              :integer
#  is_active              :boolean
#  is_sketch              :boolean
#  is_improv              :boolean
#  city_id                :integer
#

class User < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name

  validates :name, presence: true
  validates :email, presence: true, uniqueness: true, email_format: { message: 'is not a valid email.' }

  # Old recommendation system, removed for local editing.
  recommends :users
  after_like ->(u) { u.update_rating }
  after_dislike ->(u) { u.update_rating }

  has_secure_password
  has_attached_file :avatar,
    styles: {
      large: '500x500#', medium: '300x300#', small: '100x100#', thumb: '50x50#'
    },
    default_style: :small,
    default_url: '/assets/users/missing_:style.png',
    url: '/system/:class/:attachment/:id/:style/:basename.:extension',
    path: ':rails_root/public/system/:class/:attachment/:id/:style/:basename.:extension'
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

  has_one :schedule, dependent: :destroy
  has_many :experiences, dependent: :destroy
  has_many :theatres, -> { uniq }, through: :experiences
  has_many :invites, foreign_key: :owner_id
  belongs_to :invite
  belongs_to :city

  before_create :defaults, :generate_auth_token, :create_schedule, :lowercase_email

  scope :coaches, -> { where(is_coach: :t).where('is_improv = ? OR is_sketch = ?', true, true) }
  scope :improv_coaches, -> { coaches.where(is_improv: 't') }
  scope :sketch_coaches, -> { coaches.where(is_sketch: 't') }

  # Friendly ID
  friendly_id :name, use: %i[slugged history]

  # def should_generate_new_friendly_id?
  #  new_record?
  # end

  # Mail Actions
  def send_password_reset
    generate_token(:password_reset_token)
    update(password_reset_time: Time.now)
    UserMailer.password_reset(self).deliver_now
  end

  def send_coach_contact(to, body)
    UserMailer.coach_contact(self, to, body).deliver_now
  end

  def send_comment_notification(comment_data)
    UserMailer.comment_notification(self, comment_data['from']['name'], comment_data['message']).deliver_now
  end

  # Utility
  def to_s
    name
  end

  # invite Funcitons
  def add_invite
    Invite.create do |i|
      i.owner = self
    end
  end

  # Rating Functions
  def total_ratings
    liked_by_count + disliked_by_count
  end

  def calculate_rating
    total_ratings > 0 ? ((liked_by_count.to_f / total_ratings.to_f) * 100) : -1
  end

  def update_rating
    self.rating = calculate_rating
    save
  end

  # END Rating Function

  def has_experience?(theatre_id, experience_type_id)
    !experiences.where(theatre_id: theatre_id, experience_type_id: experience_type_id).empty?
  end

  def unlink!
    update!(
      uid: nil,
      provider: nil,
      oauth_token: nil,
      oauth_token_expires_at: nil
    )
  end

  private

  def defaults
    self.bio ||= ''
    self.is_coach ||= 'f'
    self.is_active ||= 't'
    self.is_improv ||= 't'
    self.is_sketch ||= 'f'
    self.is_admin ||= 'f'
    self.rating = -1
  end

  def generate_auth_token
    generate_token(:auth_token)
  end

  def generate_token(column)
    begin
      self[column] = SecureRandom.urlsafe_base64
    end while User.exists?(column => self[column])
  end

  def create_schedule
    self.schedule = Schedule.new
  end

  def lowercase_email
    email.downcase!
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

require 'open-uri'
require 'json'

class UsersController < ApplicationController
  before_action :require_login, only: %i[edit update edit_improv edit_schedule edit_endorsements edit_password delete_avatar email email_send invites unlink destroy]

  # GET /users
  # GET /users.json
  def index
    @users = current_city.coaches.joins(:schedule).order('schedules.updated_at desc').paginate(page: params[:page], per_page: 10)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  def register
    @user = User.new
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    if request.path != user_path(@user)
      redirect_to @user, status: :moved_permanently
    elsif @user&.is_coach && (@user&.is_improv || @user&.is_sketch)
      respond_to do |format|
        format.html # show.html.erb
        format.json { render json: @user }
      end
    else
      redirect_to users_url, notice: "Sorry, we couldn't find that coach."
    end
  end

  def email
    @user = User.find(params[:user_id])
  end

  def email_send
    @to_user = User.find(params[:user_id])

    if current_user && @to_user
      current_user.send_coach_contact(@to_user, params[:message])
    end

    respond_to do |format|
      format.js
    end
  end

  def comment_send
    to_user = User.find(params[:user_id])
    comment_id = params[:comment_id]
    access_token = params[:access_token]

    comment_data = JSON.parse(open("https://graph.facebook.com/v2.4/#{comment_id}?access_token=#{access_token}").read)

    if comment_data['error'].nil?
      to_user.send_comment_notification(comment_data)
    end

    respond_to do |format|
      format.json { head :ok }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # Basic edit
  def edit; end

  def edit_improv
    @other_cities = Theatre.all - current_city.theatres
  end

  def edit_schedule; end

  def edit_endorsements; end

  def edit_password; end

  def delete_avatar; end

  def invites; end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user].permit(user_allowed_attributes << 'name'))

    if (!Rails.env.production? || verify_recaptcha(model: @user)) && @user.save
      set_authorized_user(@user, false)

      if params[:invite_code]
        redirect_to invite_accept_url(code: params[:invite_code])
      else
        respond_to do |format|
          format.html { redirect_to root_url, notice: 'Welcome to ImprovCoaches.com.' }
          format.json { render json: @user, status: :created, location: @user }
        end
      end
    else
      respond_to do |format|
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(current_user.id)
    updated = false

    # Are we updating experience?
    if params[:experience_update]
      @user.experiences.destroy_all # Remove all previous experience.

      unless params[:experience].nil?
        params[:experience].each do |theatre_id, experience_types|
          experience_types.each do |experience_type_id, _val|
            Experience.create!(
              theatre_id: theatre_id,
              experience_type_id: experience_type_id,
              user_id: @user.id
            )
          end
        end
        updated = true
      end
    else
      updated = @user.update(params[:user].permit(user_allowed_attributes))
    end

    respond_to do |format|
      if updated
        format.html { redirect_to request.referer, flash: { success: 'User was successfully updated.' } }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def unlink
    @user = current_user
    @user.unlink!
    @user.send_password_reset

    respond_to do |format|
      msg = "Your facebook account has been unlinked.  A password reset email has been sent to #{@user.email} to make sure you can still log in."
      format.html { redirect_to profile_edit_path, flash: { success: msg } }
    end
  end

  def destroy
    @user = current_user
    @user.destroy!
    remove_authorized_user

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  def user_allowed_attributes
    %i[email avatar password password_confirmation is_improv is_sketch bio city_id]
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_edit_links.html.erb
<ul class="nav nav-pills nav-stacked">
	<li <%= current == :basic ? 'class=active' : '' %> ><%= link_to "Basics", profile_edit_path %></li>
	<% if current_user.is_coach %>
		<li <%= current == :schedule ? 'class=active' : '' %> ><%= link_to "Schedule", profile_edit_schedule_path %></li>
		<li <%= current == :improv ? 'class=active' : '' %> > <%= link_to "Experience", profile_edit_improv_path %></li>
		<li <%= current == :invites ? 'class=active' : '' %> > <%= link_to "Invites (" + current_user.invites.free.count.to_s + ")", profile_invites_path %></li>
		<li><%= link_to "View Public", user_path(current_user) %></li>
	<% end %>
</ul>

app/views/users/_feed_ad.html.erb
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<ins class="adsbygoogle"
        style="display:block"
        data-ad-format="fluid"
        data-ad-layout-key="-gk-1a+p-i7+16x"
        data-ad-client="ca-pub-8336284004077406"
        data-ad-slot="7786538561"></ins>
<script>
        (adsbygoogle = window.adsbygoogle || []).push({});
</script>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field"> 
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :bio %><br />
    <%= f.text_area :bio %>
  </div>
  <div class="field">
      <%= f.label :theatre_id, "Primary Theatre" %><br />
      <%= f.collection_select :theatre_id, Theatre.all, :id, :name %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>

  <% if Rails.env.production? %>
    <div class="field">
      <%= recaptcha_tags %>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/_form_theatres.html.erb
<% Theatre.all.each do |theatre| %>
  <div class="experience">
    <strong><%= theatre.name %></strong>
    <% ExperienceType.all.each do |experience_type| %>
      <%= label_tag "user_experience[#{theatre.id}][#{experience_type.id}]", experience_type.name %>
      <%= check_box_tag "user_experience[#{theatre.id}][#{experience_type.id}]",  1, current_user.has_user_experience?( theatre.id, experience_type.id) %>
    <% end %>
  </div>
<% end %>

app/views/users/_register.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, "Your Name", class: "sr-only" %>
    <%= f.text_field :name, class: "form-control", placeholder: "Full Name" %>
  </div>

  <div class="form-group">
    <%= f.label :email, "Email Address",  class: "sr-only" %>
    <%= f.text_field :email, class: "form-control", placeholder: "Email Address" %>
  </div>

  <div class="form-group">
    <%= f.label :password, "Password", class: "sr-only" %>
    <%= f.password_field :password, class: "form-control", placeholder: "Password" %>
  
    <%= f.label :password_confirmation, "Password (again)", class: "sr-only" %>
    <%= f.password_field :password_confirmation, class: "form-control", placeholder: "Confirm Password" %>
  </div>

  <% if Rails.env.production? %>
    <div class="form-group">
      <%= recaptcha_tags %>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.submit "Register", class:"btn btn-large btn-primary btn-block" %>
  </div>

  <% if(!local_assigns[:invite_code].nil?) %>
    <%= hidden_field_tag :invite_code, local_assigns[:invite_code] %>
  <% end %>
<% end %>

app/views/users/edit.html.erb
  
<div class="page-header">
  <h1>Profile</h1>
</div>
<div class="row">
  <div class="col-sm-6 col-md-2">
    <div class="panel panel-default">
      <div class="panel-heading">
        Your Profile
      </div>
      <div class="panel-body">
        <%= render "edit_links", current: :basic %>
      </div>
    </div>
  </div>
  <div class="col-sm-6 col-md-6">
    <%= form_for current_user, url: :profile_update, method: :post do |f| %>
      <% if current_user.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(current_user.errors.count, "error") %> prohibited this user from being saved:</h2>
          <ul>
            <% current_user.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <div class="form-group">
        <%= f.label :name, "Name" %>
        <%= f.text_field :name, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :email, "Email"%>
        <%= f.text_field :email, class: "form-control" %>
      </div>
      <% if(current_user.is_coach) %>
        <div class="form-group">
          <strong>I coach:</strong>
          <div class="form-input">
            <%= f.label :is_improv, class: "checkbox" do %>
              Improv
              <%= f.check_box :is_improv%>
            <% end %>
          </div>
          <div class="form-input">
            <%= f.label :is_sketch, class: "checkbox" do  %>
              Sketch
              <%= f.check_box :is_sketch %>
            <% end %>
          </div>
          <div class="form-input">
            Done coaching? Leave both unchecked and you'll no longer appear as a coach.
          </div>
        </div>
        <div class="form-group">
          <%= f.label :bio %>
          <%= f.text_area :bio, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f .label :city_id, "Current City" %>
          <%= f.collection_select :city_id, City.all, :id, :name, {}, class: "form-control" %>
        </div>
      <% else %>
        <div class="panel panel-default">
          <div class="panel-heading">
            <h3>Looking for Coach Options?</h3>
          </div>
          <div class="panel-body">
            Coach registration is currently invite only.  Coaches already on ImprovCoaches can invite new people to be coaches.  Questions?  <%= mail_to "support@improvcoaches.com", "Email us" %>
          </div>
        </div>
      <% end %>
      <div class="form-group">
        <%= f.label :password, "New Password (if changing)" %>
        <%= f.password_field :password, class: "form-control" %>
        <%= f.label :password_confirmation, "Confirm New Password" %>
        <%= f.password_field :password_confirmation, class: "form-control" %>
      </div>
      <%= f.submit "Update", class: "btn btn-primary btn-lg" %>
    <% end %>
  </div>

  <div class="col-sm-12 col-md-4">
    <% if(current_user.is_coach) %>
      <div class=row>
        <div class="panel panel-primary">
          <div class="panel-heading">
            Your Photo
          </div>
          <div class="panel-body">
            <p>
              <%= image_tag current_user.avatar.url :medium %>
              <%= form_for(current_user,
                      url: :profile_update,
                      method: :post,
                      html: {:multipart => true},
                  ) do |f| %>
                <%= f.file_field :avatar, class: "form-control btn-block" %>
                <%= f.submit "Update Avatar", class: "btn btn-default btn-large btn-block" %>
              <% end %>
            </p>
          </div>
        </div>
      </div>
      <div class="row">
        <% if(current_user.uid.present?) %>
         <div class="panel panel-primary">
            <div class="panel-heading">
              Unlink from Facebook?
            </div>
            <div class="panel-body">
              <p>
                Done with Facebook?  Unlink your account and manually reset your password.
              </p>
              <p>
                <%= link_to "Unlink", :profile_unlink, data: { confirm: "Unlink and reset password?" }, class: 'btn btn-default btn-large btn-block btn-danger'%>
              </p>
            </div>
          </div>
        <%end%>
      </div>
      <div class="row">
        <div class="panel panel-primary">
            <div class="panel-heading">
              Delete Account
            </div>
            <div class="panel-body">
              <p>
                Done with improv? Concerned about your data?  
              </p>
              <p>
                <%= link_to "Delete Account", :profile_destroy, data: { confirm: "Delete your account?  This is forever." }, class: 'btn btn-default btn-large btn-block btn-danger'%>
              </p>
            </div>
          </div>
      </div>
    <% end %>
  </div>


</div>

app/views/users/edit_password.html.erb
<h1>Update Password</h1>

<%= form_for(current_user) do |f| %>
  <% if current_user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(current_user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% current_user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit_schedule.html.erb
<div class="page-header">
	<h1>Profile</h1>
</div>

<div class="row">
    <div class="col-sm-6 col-md-2">
      <div class="panel panel-default">
        <div class="panel-heading">
          Your Profile
        </div>
        <div class="panel-body">
          <%= render "edit_links", current: :schedule %>
        </div>
      </div>
    </div>

<div class="col-sm-12 col-md-10">
	<%= render "schedules/form", schedule: current_user.schedule %>
</div>

app/views/users/email_send.js.erb
$('#email').modal('hide');
$('#email textarea').val("");
<%= render partial: "shared/alert", locals: { level: 'success', message: "Your email has been sent."} %>

app/views/users/invites.html.erb
<h1>Profile</h1>

<div class="row">

    <div class="col-sm-6 col-md-2 col-lg-2">
      <div class="panel panel-default">
        <div class="panel-heading">
          Your Profile
        </div>
        <div class="panel-body">
          <%= render "edit_links", current: :invites %>
        </div>
      </div>
    </div>

    <div class="col-sm-6 col-md-10 col-lg-10">
    	
		<div class="col-sm-6 col-md-6 col-lg-6">
		    <div class="panel panel-default">
		    	<div class="panel-heading">
		    		<h3>Invite a Friend to be a Coach</h3>
		    	</div>

		    	<div class="panel-body">
		    		<% if(!current_user.is_admin?) %>
		    			<p>You have <%= current_user.invites.free.count %> invite<%= current_user.invites.free.count != 1 ? "s" : "" %> available.</p>
		    		<% end %>
		    		<% if(current_user.invites.free.count > 0 || current_user.is_admin?) %>
			    		<%= form_tag profile_invites_path, method: :post, remote: true, class: "form-email" do %>
			    			<div class="form-group">
			    				<%= label_tag :email, "Email" %>
			    				<%= text_field_tag :email, "", class: "form-control", placeholder: "mypal@gmail.com", autofocus: "" %>
			    			</div>
			    			<%= content_tag :button, type: :submit, class: "btn btn-primary btn-small btn-block" do %>
								Invite
								<span></span>
							<% end %>
			    		<% end %>
			    	<% end %>
		    	</div>
		    </div>
	    </div>

		<% if(current_user.invites.sent.count > 0) %>
			<div class="col-sm-12 col-md-10">
				<h3>Past Invites</h3>
				<table class="table" id="invites">
					<thead>
						<th>Sent To</th>
						<th>Status</th>
						<th></th>
						<th></th>
						<th></th>
					</thead>
					<tbody>
						<% current_user.invites.sent.each do |invite| %>
							<%= render partial: "invites/invite", object: invite %>
						<% end %>
					</tbody>
				</table>
			</div>
		<% end %>
	</div>
</div>

app/views/users/show.html.erb
<% set_meta_tags title: @user.name, reverse: true %>
<% set_meta_tags canonical: user_url(@user) %>

<% content_for :open_graph do %>
	<meta property="fb:app_id" body="140954086073433" /> 
	<meta property="og:type" body="website" /> 
	<meta property="og:title" body="<%= @user.name %>" /> 
	<meta property="og:image" body="<%= @user.avatar.url(:medium) %>" /> 
	<meta property="og:description" body="<%= @user.name %> on ImprovCoaches.com" /> 
	<meta property="og:url" body="<%= user_url @user %>">
	<meta property="fb:profile" body="<%= @user.uid %>" />
<% end %>

<div id="show">
	<div class="container">
		<h1>
			<%= @user.name %>

			<% if(params[:from_search]) %>
				<%= link_to "Back to Results", search_path( { page: params[:page] } ) , { id: :back_to } %>
			<% end %>
		</h1>
		
		<div class="row">
			<div class="col-sm-6 col-md-3">
				<div class="row">
					<div class="thumbnail">
						<%= image_tag @user.avatar.url(:medium), { class: :avatar } %>
					</div>
				</div>
				<div class="row">
					<div id="contact" class="caption">
						<% if current_user && @user.id == current_user.id && !current_user.is_admin %>
			    			This is you.  <%= link_to 'Update Your Profile', profile_edit_path %>
						<% else %>
							<div class="rating" data-userid="<%= @user.id%>">
								<%= render partial: "ratings/rating", locals: { user: @user } %>
							</div>
							
							<div class="left-actions btn-block">
								<% if(current_user) %>
									<a data-toggle="modal" href="#email" class="btn btn-primary btn-lg btn-block">
										<span class="glyphicon glyphicon-envelope"></span> Email
									</a>
								<% else %>
									<a href="<%= user_email_path(@user)%>" class="btn btn-primary btn-lg btn-block" data-remote="true">
										<span class="glyphicon glyphicon-envelope"></span> Email
									</a>
								<% end %>
							<% end %>
							<div>
								<div class="fb-share-button" data-href="<%= user_url @user %>" data-type="button"></div>
								<div id="twitter"><a href="https://twitter.com/share" class="twitter-share-button">Tweet</a></div>
								<script>
								!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');
								</script>
							</div>
						</div>
					</div>
				</div>
				<div class="row">
					<%= render partial: 'users/show_ad' %>
				</div>
			</div>

			<div class="col-sm-6 col-md-9">
				<div class="user-frames">
					<div id="bio" class="panel panel-default">
						<div class="panel-heading">
							About
						</div>
						<div class="panel-body">
							<div>
								<%= simple_format @user.bio  %>
							</div>
							<div class="experience">
								<%= render "experience" %>
							</div>
						</div>
					</div>

					<div id="feedback" class="panel panel-default">
						<div class="panel-heading">
							Feedback
						</div>
						<div class="panel-body">
							<div class="fb-comments" data-href="<%= user_url(@user).gsub('s:', ':') %>" data-num-posts="10" data-order-by="reverse_time" data-width="100%"></div>
						</div>
					</div>
					
					<div id="availability" class="panel panel-default">
						<div class="panel-heading">
							Availability
						</div>
						<div class="panel-body">
							<%= render 'schedules/mini', schedule: @user.schedule %>
						</div>
					</div>
					
					<div id="likes" class="panel panel-default">
						<div class="panel-heading">
							Recommended Coaches
						</div>
						<div class="panel-body">
							<%= render 'ratings/bookmarks', user: @user %>
						</div>
					</div>
				
					
					
				</div>

			</div>
		</div>		

		<% #Modal window for email %>
		<%= render partial: "email", locals: { user: @user } if current_user %>
	</div>
</div>