config/routes.rb
# frozen_string_literal: true

Improvcoaches::Application.routes.draw do
  root to: 'home#index'
  get '/about', to: 'home#about'
  get '/splash', to: 'home#splash'
  match '/search', to: 'search#search', via: %i[post get]
  get '/improv-books', to: 'home#resources', as: 'resources'

  controller :auth do
    get  'login' => :new
    post 'login' => :create
    get  'logout' => :destroy

    get 'link' => :link
    post 'link' => :confirm_link
  end

  # Omniauth
  get 'auth/:provider/callback', to: 'auth#create', from_facebook: true
  get 'auth/failure', to: 'auth#failure'
  get 'signout', to: 'auth#destroy', as: 'signout'

  controller :users do
    get 'join' => :new
    get 'profile' => :show, profile: true
    get 'profile/invites' => :invites
    post 'profile/invites' => 'invites#invite_send'
    get 'profile/invites/:code/resend' => 'invites#resend', as: 'profile_invite_resend', defaults: { format: 'js' }
    get 'profile/invites/:code/cancel' => 'invites#cancel', as: 'profile_invite_cancel', defaults: { format: 'js' }
    get 'profile/edit' => :edit
    get 'profile/unlink' => :unlink
    get 'profile/destroy' => :destroy
    get 'profile/edit/improv' => :edit_improv
    get 'profile/edit/schedule' => :edit_schedule
    get 'profile/edit/password' => :edit_password
    post 'profile/update' => :update
    delete 'profile/edit/avatar' => :delete_avatar
  end

  controller :schedules do
    post 'profile/edit/schedule' => :update
  end

  controller :invites do
    get 'invite/:code' => :landing, as: 'invite_landing'
    get 'invite/:code/accept' => :accept, as: 'invite_accept'
  end

  resources :users, path: 'coaches' do
    controller :ratings do
      get 'like' => :like, defaults: {format: :js }
      get 'dislike' => :dislike, defaults: {format: :js }
      get 'bookmark' => :bookmark, defaults: {format: :js }
    end

    get 'email' => :email
    post 'email' => :email_send, defaults: {format: :js }
    post 'comment' => :comment_send, defaults: {format: :js }
  end

  resources :spaces do
    patch 'image' => :add_image
    delete 'image/:id' => :delete_image
  end

  resources :password_resets
  resources :theatres
  resources :substitution_requests
end

app/models/schedule.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: schedules
#
#  id         :integer          not null, primary key
#  user_id    :integer
#  name       :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#


class Schedule < ActiveRecord::Base
  belongs_to :user
  has_many :time_blocks

  def has_block?(day, hour, minute)
    time_blocks.any? do |block|
      block.day == day &&
        block.hour == hour &&
        block.minute == minute
    end
  end

  def has_time_span(start_hour, start_minute, end_hour, end_minute, day)
    h = start_hour
    m = start_minute
    d = day
    success = true

    end_hour = start_hour if end_hour.nil?
    end_hour = start_minute if end_minute.nil?

    while h < end_hour || (h == end_hour && m <= end_minute)
      if time_blocks.where(
        hour: h,
        minute: m,
        day: d
      ).first.nil?
        success = false
        break
      else
        m += 30
        h += 1 if m >= 60
        m = 0 if m >= 60
      end
    end

    success
  end

  def first_hour_available
    first_block = time_blocks.order('hour asc').first

    first_block&.hour
  end

  def last_hour_available
    first_block = time_blocks.order('hour desc').first

    first_block&.hour
  end
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController

  before_filter :require_login, only: [:edit, :update]
  
  # GET /schedules
  # GET /schedules.json
  def index
    @schedules = Schedule.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @schedules }
    end
  end

  # GET /schedules/1
  # GET /schedules/1.json
  def show
    @schedule = Schedule.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @schedule }
    end
  end

  # GET /schedules/new
  # GET /schedules/new.json
  def new
    @schedule = Schedule.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @schedule }
    end
  end

  # GET /schedules/1/edit
  def edit
    @schedule = Schedule.find(params[:id]) 
  end

  # POST /schedules
  # POST /schedules.json
  def create
    @schedule = Schedule.new(params[:schedule])

    respond_to do |format|
      if @schedule.save
        format.html { redirect_to @schedule, notice: 'Schedule was successfully created.' }
        format.json { render json: @schedule, status: :created, location: @schedule }
      else
        format.html { render action: "new" }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /schedules/1
  # PUT /schedules/1.json
  def update
    @schedule = current_user.schedule
    days = [ "Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday" ]

    if(@schedule.nil?) then #create new schedule if it doesn't exist
      @schedule = Schedule.new
      @schedule.user_id = current_user.id
      @schedule.save
    end

    new_blocks = []
    
    #Get rid of the old guys.
    @schedule.time_blocks.delete_all
    
    if(params['time_blocks']) then
      params['time_blocks'].each do |i, param_block|
        @schedule.transaction do
          new_blocks << @schedule.time_blocks.create(
            day: days.index(param_block[:day]),
            hour: param_block[:hour],
            minute: param_block[:minute]
          )
        end
      end
    end
    
    respond_to do |format|
      if @schedule.touch
        format.html { redirect_to :profile_edit_schedule, notice: 'Schedule was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schedules/1
  # DELETE /schedules/1.json
  def destroy
    @schedule = Schedule.find(params[:id])
    @schedule.destroy

    respond_to do |format|
      format.html { redirect_to schedules_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/views/schedules/_form.html.erb
<% days = [ "Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"] %>

<table class="schedule_editor table table-condensed">
  <thead>
    <% for day in days do%>
      <th><%= day %>
    <% end %>
  </thead>

  <% fraction = 0.5 %>
  <% hour = 8 %>
  <% end_hour = 23 %>
  <tbody>
    <%  for h in hour..end_hour do%>
      <% (1/fraction).to_i.times do |i| %>
        <tr>
          <% m = ((60 / (i+1)) - 60 ).abs %>
          
          <% 7.times do |d| %>
            <td class="time_block <%= schedule.has_block?(d, h, m) ? 'success' : '' %>">
              <span class="day"><%= days[d] %></span>
              <span class="hour"><%= h %></span>&#58;<span class="minute"><%= m.to_s.rjust(2, "0") %></span>
            </td>
          <% end %>
        </tr>
      <% end %>
    <% end %>

  </tbody>
</table>

<form class="schedule" method='post'>
  <%= token_tag form_authenticity_token.to_s %>
</form>
<button class="pull-right btn btn-primary btn-large update_schedule" >Update Schedule</button>

app/views/schedules/_mini.html.erb
<% days = [ "Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"] %>

<% fraction = 0.5 %>

<% if !schedule.nil? && 
      first_hour = schedule.first_hour_available && 
      last_hour  = schedule.last_hour_available then %>
  <div class="table-responsive">
    <table class="table table-condensed table-bordered table-hover">
      <thead>
        <th></th>
        <% for day in days do%>
          <th><%= day %>
        <% end %>
      </thead>

      <tbody>
        
        <%  for h in schedule.first_hour_available..schedule.last_hour_available do%>
          <% (1/fraction).to_i.times do |i| %>
            <tr>
              <% m = ((60 / (i+1)) - 60 ).abs %>
              <% if(i == 0 ) then %>
                <% suffix = ( h >= 12) ? 'pm' : 'am' %>
                <% display_h = ( h > 12) ? h-12 : h %>
                <td class='time_of_day hour'><%= display_h.to_s + ":00" + suffix %></td>
              <% else %>
                <td class='time_of_day half'> :<%= m %> &nbsp;&nbsp;&nbsp; </td>
              <% end %>
            
              <% 7.times do |d| %>
                <td class="time_block <%= schedule.has_block?(d, h, m) ? 'success' : 'error' %>">
                  
                </td>
              <% end %>
            </tr>
          <% end %>
        <% end %>

      </tbody>
    </table>
    <small class="pull-right">Green = Available</small>
    <span id="last_updated">Last updated <%= time_ago_in_words(schedule.updated_at) %> ago</span>
  </div>
<% else %>
    <h3>No Availability Listed</h3>
<% end %>

app/views/schedules/edit.html.erb
<h1>Editing schedule</h1>

<%= render 'form' %>

<%= link_to 'Show', @schedule %> |
<%= link_to 'Back', schedules_path %>

app/views/schedules/index.html.erb
<h1>Listing schedules</h1>

<table>
  <tr>
    <th>User</th>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @schedules.each do |schedule| %>
  <tr>
    <td><%= schedule.user_id %></td>
    <td><%= schedule.name %></td>
    <td><%= link_to 'Show', schedule %></td>
    <td><%= link_to 'Edit', edit_schedule_path(schedule) %></td>
    <td><%= link_to 'Destroy', schedule, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Schedule', new_schedule_path %>

app/views/schedules/new.html.erb
<h1>New schedule</h1>

<%= render 'form' %>

<%= link_to 'Back', schedules_path %>

app/views/schedules/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @schedule.user_id %>
</p>

<p>
  <b>Name:</b>
  <%= @schedule.name %>
</p>


<%= link_to 'Edit', edit_schedule_path(@schedule) %> |
<%= link_to 'Back', schedules_path %>